cfmesh patch assignment fixed

diff --git a/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/Allrun b/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/Allrun
--- a/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/Allrun
+++ b/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/Allrun
@@ -5,37 +5,39 @@ cd "${0%/*}" || exit                                # Run from this directory
 . ./caseParams.sh                                   # Case parameters
 #------------------------------------------------------------------------------
 
-need_cmd()
-{
-    if ! command -v "$1" >/dev/null 2>&1; then
-        echo "Error: required command '$1' not found in PATH" >&2
+case "${MESHER:-gmsh}" in
+    gmsh|cfmesh)
+        ;;
+    *)
+        echo "Error: unsupported MESHER='${MESHER}'. Use 'gmsh' or 'cfmesh'." >&2
         exit 1
-    fi
-}
-
-need_cmd cartesian2DMesh
-need_cmd extrudeMesh
-
-if [ -z "${NPROCS:-}" ]; then
-    NPROCS="$(awk '/^[[:space:]]*numberOfSubdomains[[:space:]]+/ {gsub(/;/, "", $2); print $2; exit}' system/decomposeParDict)"
-fi
-: "${NPROCS:=8}"
+        ;;
+esac
 
 ./Allclean
 ./prepareCase
 
-runApplication cartesian2DMesh
-runApplication extrudeMesh
-./postMesh
+case "${MESHER:-gmsh}" in
+    gmsh)
+        restore0Dir
+        gmsh -0 constant/levitatorWedgeHex.geo
+        runApplication gmshToFoam  constant/levitatorWedgeHex.msh
+        rm constant/levitatorWedgeHex.msh
+        runApplication changeDictionary
+        ;;
+    cfmesh)
+        runApplication cartesian2DMesh
+        runApplication extrudeMesh
+        ./postMesh
+        restore0Dir
+        ;;
+esac
 
-restore0Dir
 runApplication setAlphaField
 rm -f 0/Pim.in
 
-need_cmd setPMLFields
-runApplication setPMLFields -lib libVoF.so
+runApplication setPMLFields
 
-need_cmd "${SOLVER}"
 rm -f "log.${SOLVER}"
 runApplication decomposePar -force
 runParallel "${SOLVER}"
diff --git a/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/prepareCase b/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/prepareCase
--- a/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/prepareCase
+++ b/run/acousticTests/FrequencyDomainTests/Andrade2019/WedgeLevitatorDropContactDynamic/prepareCase
@@ -41,6 +41,9 @@ render()
         -e "s|__RR__|$RR|g" \
         -e "s|__BU__|$BU|g" \
         -e "s|__HS__|$HS|g" \
+        -e "s|__MESH_N__|$MESH_N|g" \
+        -e "s|__MESH_LC__|$MESH_LC|g" \
+        -e "s|__ROTATE_HALF_DEG__|$ROTATE_HALF_DEG|g" \
         -e "s|__WEDGE_DEG__|$WEDGE_DEG|g" \
         -e "s|__DROP_RADIUS__|$DROP_RADIUS|g" \
         -e "s|__DROP_CENTER_Y__|$DROP_CENTER_Y|g" \
@@ -51,12 +54,19 @@ render constant/transportProperties.in constant/transportProperties
 render 0.orig/Pim.in 0.orig/Pim
 render system/setAlphaFieldDict.in system/setAlphaFieldDict
 
-export D RT RR BU HS WEDGE_DEG AXIS_RADIUS SURFACE_THICKNESS
-export CFMESH_MAX_CELL_SIZE CFMESH_INTERFACE_REFINEMENT
-export CFMESH_INTERFACE_CELL_SIZE CFMESH_INTERFACE_BOX_SCALE
-export DROP_RADIUS DROP_CENTER_Y
+case "${MESHER:-gmsh}" in
+    gmsh)
+        rm -f constant/levitator2D.fms system/meshDict system/extrudeMeshDict
+        render constant/levitatorWedgeHex.geo.in constant/levitatorWedgeHex.geo
+        ;;
+    cfmesh)
+        rm -f constant/levitatorWedgeHex.msh constant/*unrolled*
+        export D RT RR BU HS WEDGE_DEG AXIS_RADIUS SURFACE_THICKNESS
+        export CFMESH_MAX_CELL_SIZE CFMESH_INTERFACE_REFINEMENT
+        export CFMESH_INTERFACE_CELL_SIZE CFMESH_INTERFACE_BOX_SCALE
+        export DROP_RADIUS DROP_CENTER_Y
 
-python3 - <<'PY'
+        python3 - <<'PY'
 from os import environ
 from pathlib import Path
 
@@ -113,18 +123,19 @@ points2d = [
     (AXIS_RADIUS, D),
 ]
 
+# Match the Gmsh physical surfaces for the same wedge geometry.
 segment_patches = [
-    "transducer1",
     "reflector1",
     "reflector1",
-    "openAir",
-    "openAir",
-    "openAir",
-    "openAir",
-    "openAir",
-    "openAir",
     "reflector2",
+    "openAir",
+    "openAir",
+    "openAir",
+    "openAir",
+    "openAir",
+    "openAir",
     "transducer2",
+    "transducer1",
     "axis",
 ]
 
@@ -242,3 +253,9 @@ mergeFaces false;
 """
 (system / "extrudeMeshDict").write_text(extrude_dict)
 PY
+        ;;
+    *)
+        echo "Error: unsupported MESHER='${MESHER}'. Use 'gmsh' or 'cfmesh'." >&2
+        exit 1
+        ;;
+esac
